version: '3.8'


services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db_receitas
    depends_on:
      - db
    volumes:
      - /app/node_modules
    command: sh -c "npm run build && npm start"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_receitas
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 